"""
Atlas OS - Web Tool Layer

Provides a unified interface for agents to perform web queries.
This is a lightweight abstraction that can later be connected to:
- search APIs
- browser agents
- scraping tools

For now, it supports a simple mock + optional HTTP endpoint mode.
"""

import os
import json
import urllib.request
from typing import Dict, Any


class WebTool:
    def __init__(self):
        self.mode = os.getenv("WEB_TOOL_MODE", "mock")
        self.search_endpoint = os.getenv("WEB_SEARCH_ENDPOINT", "")

    def search(self, query: str) -> Dict[str, Any]:
        if self.mode == "mock":
            return self._mock_search(query)

        if self.mode == "api" and self.search_endpoint:
            return self._api_search(query)

        return self._mock_search(query)

    def _api_search(self, query: str) -> Dict[str, Any]:
        try:
            payload = json.dumps({"query": query}).encode("utf-8")

            req = urllib.request.Request(
                self.search_endpoint,
                data=payload,
                headers={"Content-Type": "application/json"}
            )

            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except Exception as e:
            return {"error": str(e), "results": []}

    def _mock_search(self, query: str) -> Dict[str, Any]:
        return {
            "query": query,
            "results": [
                {
                    "title": "Simulated result for " + query,
                    "snippet": "This is a placeholder result generated by Atlas OS WebTool.",
                    "url": "https://example.com/search?q=" + query.replace(" ", "+")
                }
            ]
        }
